//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AasthaFinance.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Client 
    {
        public Client()
        {
            this.LoanApplications = new HashSet<LoanApplication>();
            this.LoanDisbursements = new HashSet<LoanDisbursement>();
            this.LoanRepayments = new HashSet<LoanRepayment>();
        }
    
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public string FatherName { get; set; }
        public string CurrentAddress { get; set; }
        public string Post { get; set; }
        public string District { get; set; }
        public string PinCode { get; set; }
        public string ClientCode { get; set; }
        public Nullable<int> GenderId { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PersonalContact { get; set; }
        public string OfficeContact { get; set; }
        public string ClientImage { get; set; }
        public Nullable<int> UserId { get; set; }
        public string State { get; set; }
        public string Notes { get; set; }
        public Nullable<int> BranchId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<LoanApplication> LoanApplications { get; set; }
        public virtual ICollection<LoanDisbursement> LoanDisbursements { get; set; }
        public virtual ICollection<LoanRepayment> LoanRepayments { get; set; }
    }
}
