//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AasthaFinance.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LoanPreClosing
    {
        public int LoanPreClosingId { get; set; }
        public Nullable<int> LoanDisbursementId { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> PreClosingCharges { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> ActualLoanBalance { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
    
        public virtual LoanDisbursement LoanDisbursement { get; set; }
        public virtual User User { get; set; }
    }
}
