//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AasthaFinance.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LoanEMISchedule
    {
        public LoanEMISchedule()
        {
            this.LoanRepayments = new HashSet<LoanRepayment>();
        }
    
        public int LoanEMIScheduleId { get; set; }
        public Nullable<int> LoanDisbursementId { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> EMIDate { get; set; }
        public Nullable<decimal> EMI { get; set; }
        public Nullable<decimal> PrincipleAmount { get; set; }
        public Nullable<decimal> InterestAmount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Notes { get; set; }
    
        public virtual LoanDisbursement LoanDisbursement { get; set; }
        public virtual ICollection<LoanRepayment> LoanRepayments { get; set; }
    }
}
