//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AasthaFinance.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LoanDisbursement
    {
        public LoanDisbursement()
        {
            this.LoanEMISchedules = new HashSet<LoanEMISchedule>();
            this.LoanPreClosings = new HashSet<LoanPreClosing>();
            this.LoanRepayments = new HashSet<LoanRepayment>();
        }
    
        public int LoanDisbursementId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> LoanApplicationId { get; set; }
        public Nullable<int> PaymentModeId { get; set; }
        public string DisbursementCode { get; set; }
        public string BankName { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DisbursmentDate { get; set; }
        public string PaymentChequeNo { get; set; }
        public Nullable<int> LoanCycleId { get; set; }
        public Nullable<decimal> ProposedAmount { get; set; }
        public Nullable<decimal> ProcessingCharge { get; set; }
        public Nullable<decimal> ActualPaidAmount { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> EMIStartDate { get; set; }
        public Nullable<int> LoanRepayFreequencyId { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<decimal> LoanEMI { get; set; }
        public Nullable<int> TimePeriod { get; set; }
        public Nullable<decimal> TotalRepayAmountWithInterest { get; set; }
        public Nullable<int> LoanStatusId { get; set; }
        public string LoanNotes { get; set; }
        public Nullable<decimal> LoanRepayBalance { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Client Client { get; set; }
        public virtual Freequency Freequency { get; set; }
        public virtual LoanApplication LoanApplication { get; set; }
        public virtual LoanCycle LoanCycle { get; set; }
        public virtual LoanStatu LoanStatu { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<LoanEMISchedule> LoanEMISchedules { get; set; }
        public virtual ICollection<LoanPreClosing> LoanPreClosings { get; set; }
        public virtual ICollection<LoanRepayment> LoanRepayments { get; set; }
    }
}
