//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AasthaFinance.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanCycle
    {
        public LoanCycle()
        {
            this.LoanDisbursements = new HashSet<LoanDisbursement>();
            this.LoanRepayments = new HashSet<LoanRepayment>();
        }
    
        public int LoanCycleId { get; set; }
        public string LoanCycle1 { get; set; }
    
        public virtual ICollection<LoanDisbursement> LoanDisbursements { get; set; }
        public virtual ICollection<LoanRepayment> LoanRepayments { get; set; }
    }
}
