//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AasthaFinance.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanRepaymentStatu
    {
        public LoanRepaymentStatu()
        {
            this.LoanRepayments = new HashSet<LoanRepayment>();
        }
    
        public int LoanRepaymentStatusId { get; set; }
        public string LoanRepaymentStatus { get; set; }
    
        public virtual ICollection<LoanRepayment> LoanRepayments { get; set; }
    }
}
