//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AasthaFinance.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class LoanRepayment
    {
        public int LoanRepaymentId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> LoanApplicationId { get; set; }
        public Nullable<int> LoanDisbursementId { get; set; }
        public Nullable<int> LoanCycleId { get; set; }
        public Nullable<int> LoanEMIScheduletId { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> LateFees { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public Nullable<int> RepaymentStatusId { get; set; }
        public string Notes { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Client Client { get; set; }
        public virtual LoanApplication LoanApplication { get; set; }
        public virtual LoanCycle LoanCycle { get; set; }
        public virtual LoanDisbursement LoanDisbursement { get; set; }
        public virtual LoanEMISchedule LoanEMISchedule { get; set; }
        public virtual LoanRepaymentStatu LoanRepaymentStatu { get; set; }
        public virtual User User { get; set; }
    }
}
