//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AasthaFinance.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplicationStatu
    {
        public LoanApplicationStatu()
        {
            this.LoanApplications = new HashSet<LoanApplication>();
        }
    
        public int LoanApplicationStatusId { get; set; }
        public string LoanApplicationStatus { get; set; }
    
        public virtual ICollection<LoanApplication> LoanApplications { get; set; }
    }
}
