//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AasthaFinance.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Clients = new HashSet<Client>();
            this.LoanApplications = new HashSet<LoanApplication>();
            this.LoanDisbursements = new HashSet<LoanDisbursement>();
            this.LoanPreClosings = new HashSet<LoanPreClosing>();
            this.LoanRepayments = new HashSet<LoanRepayment>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<LoanApplication> LoanApplications { get; set; }
        public virtual ICollection<LoanDisbursement> LoanDisbursements { get; set; }
        public virtual ICollection<LoanPreClosing> LoanPreClosings { get; set; }
        public virtual ICollection<LoanRepayment> LoanRepayments { get; set; }
        public virtual Role Role { get; set; }
    }
}
